// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phone_Book.Persistence;

#nullable disable

namespace Phone_Book.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Phone_Book.Domain.Phone_Number", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Phones_BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Phones_BookId");

                    b.ToTable("Phone_Number");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eab8db3e-5749-4dc5-a877-312216df4c6b"),
                            Number = "01065232323",
                            Phones_BookId = new Guid("5ccdaab9-8b91-42b0-aede-51d42810d2d8")
                        },
                        new
                        {
                            Id = new Guid("eab8db99-5749-4dc5-a877-312216df4c6b"),
                            Number = "01065232323",
                            Phones_BookId = new Guid("5ccdaab9-8b91-42b0-aede-51d42810d2d8")
                        });
                });

            modelBuilder.Entity("Phone_Book.Domain.Phones_Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Phone_Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ccdaab9-8b91-42b0-aede-51d42810d2d8"),
                            Address = "assiut",
                            Name = "Ali",
                            UserId = new Guid("6b305129-ac8a-4a31-9107-ecb8c2c3dc2d")
                        });
                });

            modelBuilder.Entity("Phone_Book.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b305129-ac8a-4a31-9107-ecb8c2c3dc2d"),
                            FirstName = "Mahmoud",
                            LastName = "Hussein",
                            Password = "987654321",
                            UserName = "hussein98"
                        });
                });

            modelBuilder.Entity("Phone_Book.Domain.Phone_Number", b =>
                {
                    b.HasOne("Phone_Book.Domain.Phones_Book", "Phones_Book")
                        .WithMany("Phone_Numbers")
                        .HasForeignKey("Phones_BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phones_Book");
                });

            modelBuilder.Entity("Phone_Book.Domain.Phones_Book", b =>
                {
                    b.HasOne("Phone_Book.Domain.User", "User")
                        .WithMany("Phone_Books")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Phone_Book.Domain.Phones_Book", b =>
                {
                    b.Navigation("Phone_Numbers");
                });

            modelBuilder.Entity("Phone_Book.Domain.User", b =>
                {
                    b.Navigation("Phone_Books");
                });
#pragma warning restore 612, 618
        }
    }
}
